# Generated by Django 4.1.3 on 2022-11-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_typecontac'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeContac',
            new_name='TypeContact',
        ),
    ]
