# Generated by Django 4.1.3 on 2022-12-28 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0001_initial'),
        ('comment', '0006_contact_type_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listelement.element'),
        ),
    ]
