# Generated by Django 4.1.3 on 2023-01-04 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='price',
            field=models.DecimalField(decimal_places=2, default=6.1, max_digits=10),
        ),
        migrations.AddField(
            model_name='element',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
